export const REQUEST_POSITIONS = 'REQUEST_POSITIONS';
export const REQUEST_POSITIONS_SUCCESS = 'REQUEST_POSITIONS_SUCCESS';
export const REQUEST_TEAMS = 'REQUEST_TEAMS';
export const REQUEST_TEAMS_SUCCESS = 'REQUEST_TEAMS_SUCCESS';
export const REQUEST_TEAMS_EMPLOYEES = 'REQUEST_TEAMS';
export const REQUEST_TEAMS_EMPLOYEES_SUCCESS =
  'REQUEST_TEAMS_EMPLOYEES_SUCCESS';
export const REQUEST_ADD_EMPLOYEE = 'REQUEST_ADD_EMPLOYEE';
export const REQUEST_ADD_EMPLOYEE_SUCCESS = 'REQUEST_ADD_EMPLOYEE_SUCCESS';
